---
- hosts: all
  vars:
    username: vagrant
  tasks:
    - include: ./tasks/base.yml
    - include: ./tasks/git.yml
    # - include: ./tasks/nodejs_4.x.yml
    # - include: ./tasks/nodejs_5.x.yml
    - include: ./tasks/nodejs_6.x.yml
    - include: ./tasks/nvm.yml
    - include: ./tasks/vim-pathogen.yml
    - include: ./tasks/vim-theme-atom-dark.yml
    - include: ./tasks/vimx.yml
    - include: ./tasks/atom.yml
    - include: ./tasks/atom-packages-generic.yml
    - include: ./tasks/atom-packages-java.yml
    - include: ./tasks/atom-packages-nodejs.yml
    - include: ./tasks/atom-packages-web.yml
    - include: ./tasks/kupfer.yml
    - include: ./tasks/leafpad.yml
    - include: ./tasks/chromium.yml
    # - include: ./tasks/google-chrome.yml
    - include: ./tasks/oraclejdk8.yml
    # - include: ./tasks/openjdk8.yml
    - include: ./tasks/microsoft-fonts.yml
    - include: ./tasks/open-sans.yml
